spring:
  r2dbc:
    url: r2dbc:pool:mariadb://10.0.0.52:3306/halodb
    username: root
    password: 226217@Nbs
  sql:
    init:
      mode: always
      platform: mysql
      continue-on-error: true
halo:
  console:
    proxy:
      endpoint: http://localhost:3000/
      enabled: true
  security:
    initializer:
      super-admin-username: admin
      super-admin-password: admin